Part3
ClawGibson/DietaSoAPI pull request #96
Opened 2021-11-24 02:23 UTC by OctavioBautista

2021-11-24 16:14 UTC, ClawGibson requested changes
Aunque no se vaya a utilizar la parte de los sockets, incluir su controlador.

2021-11-24 16:14 UTC, ClawGibson commented on app.js
> -const { socketController } = require('./sockets/socket.controller');
Sin el controlador del socket no existe comunicación entre sockets.

2021-11-24 16:14 UTC, ClawGibson commented on app.js
> +);
Al crearse la conexión solo imprimirá un mensaje en consola de que se conectó, pero no se podrá utilizar con los escuchadores.

2021-11-26 20:58 UTC, ClawGibson approved these changes

2021-11-26 21:11 UTC, ClawGibson requested changes
Corregir el controlador de los sockets.

2021-11-26 21:17 UTC, ClawGibson approved these changes

2021-11-26 21:18 UTC, merged

2021-11-26 21:19 UTC, OctavioBautista commented
modificado